### ISSUE TITLE
Nightly builds generation

### ISSUE THREAD

**Issue by OctoNezd** [adrifcastr/NTRDBI#10]
- [x] Upload builds to server
- [ ] Night builds channel in NTRDBI support
- [x] Maybe QR Generation for nightly(Will require creating a website)?

**Comment by OctoNezd** [comment]
Working on it right now in NTRDBI/appveyor-support

**Comment by OctoNezd** [comment]
Have problems with citro3D lib, is it really required for building?

**Comment by Jolty95** [comment]
Yes because citro is used to GPU render text and images.

**Comment by Jolty95** [comment]
@OctoNezd Only one thing. 
When I had done things with travis, I have used a fork to don't "dirty" the main repo. Would you mind to just send the specific file to master instead of merging new branch on master? There are a lot of commits with "weirds" names and most of them doesn't work

(Just in my honest oppinion) :)

**Comment by OctoNezd** [comment]
Currently I am trying to understand why https://ci.appveyor.com/project/OctoNezd/ntrdbi/build/NIGHTLY-appveyor-support-43#L31 it wont get where is ctrulib located.

**Comment by OctoNezd** [comment]
> Yes because citro is used to GPU render text and images.

Isnt it included with ctrulib?

**Comment by Jolty95** [comment]
AFAIK, it's a different library

Also, that log seems like devkitpro is not installed, only decompressed

**Comment by OctoNezd** [comment]
Wait, is it required to install? I added all vars, it should work(technically)

**Comment by Jolty95** [comment]
Of course devkit must be installed!! hahaha :P 
Only libs needs make install to work :P

**Comment by OctoNezd** [comment]
So what should I add into install script?

**Comment by Jolty95** [comment]
Something like this -> https://github.com/adrifcastr/NTRDBI/blob/master/.travis.yml#L11

**Comment by OctoNezd** [comment]
I tried to use devkitpro updater, but it doesnt have command line switches, AFAIK

**Comment by OctoNezd** [comment]
The problem is appveyor is Windows

**Comment by Jolty95** [comment]
There is available devkitpro for windows
I compile with windows 10

**Comment by Jolty95** [comment]
https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/devkitProUpdater-1.6.0.exe/download

**Comment by OctoNezd** [comment]
I talked about this automated installer. Sadly, it doesnt have command line switches, as I know

**Comment by Jolty95** [comment]
Then, I'm out of ideas

**Comment by OctoNezd** [comment]
I will try to make .pl updater work with MSYS

**Comment by Jolty95** [comment]
.pl wants system be linux or osx, but try it if you want :)

**Comment by OctoNezd** [comment]
I hope it will work with MSYS

**Comment by OctoNezd** [comment]
I already tried it running via windows perl, it didnt worked. Hope MSYS way will work

**Comment by OctoNezd** [comment]
https://ci.appveyor.com/project/OctoNezd/ntrdbi/build/NIGHTLY-appveyor-support-48#L17
Looks like it doesnt like windows

**Comment by OctoNezd** [comment]
https://ci.appveyor.com/project/OctoNezd/ntrdbi/build/NIGHTLY-appveyor-support-55#L61
It really strange issue...

**Comment by Jolty95** [comment]
appveyor doesn't support using another OS?

**Comment by OctoNezd** [comment]
Sadly

**Comment by Jolty95** [comment]
It's really strange...
Just don't worry, take a break if you want. Appveyor don't need to be setup right now and you have spend all morning on this so, take a break if you want and continue later :)

**Comment by OctoNezd** [comment]
The same error occured when it tries to build citro3d...

**Comment by OctoNezd** [comment]
https://devkitpro.org/viewtopic.php?f=3&t=2182
That is only which came up for me...

**Comment by Jolty95** [comment]
mmm I don't think them are related tbh

**Comment by OctoNezd** [comment]
So, using appveyor's MSYS, it actuall shows other error:
`execvp: make: File or path name too long`

**Comment by OctoNezd** [comment]
So I think it problem with path var, it is quite long:https://ci.appveyor.com/project/OctoNezd/ntrdbi/build/NIGHTLY-appveyor-support-60#L39

**Comment by OctoNezd** [comment]
I think I would better add artifacts sender for travis builds...

**Comment by Jolty95** [comment]
That can be done??

**Comment by OctoNezd** [comment]
Or even better, mine CI...

**Comment by OctoNezd** [comment]
> That can be done??

You can specify what happens on successful build, or if you have Amazon S3:https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by Jolty95** [comment]
Oh, didn't now that

**Comment by OctoNezd** [comment]
I will to work on mine travis artifacts

**Comment by OctoNezd** [comment]
I implemented server, but there is some strange things happening, it just wont work...
![image](https://cloud.githubusercontent.com/assets/15308404/24072996/03a4f936-0c01-11e7-8be4-f784172f47b1.png)

**Comment by Jolty95** [comment]
I can't help you with that. I don't know Python...

**Comment by OctoNezd** [comment]
nvm, problem were in that I used ntrdb domain, which is http-only

**Comment by OctoNezd** [comment]
Update:[site works](stuff.octonezd.pw:8800)

**Comment by OctoNezd** [comment]
Now only make little script for uploading builds, and we are done!

**Comment by Jolty95** [comment]
Really like the site!!

**Comment by Jolty95** [comment]
btw, when you are done, remove any unused branch if any :P 
(I really like to have repo as clean as possible xDD)

**Comment by OctoNezd** [comment]
You can remove appveyor-support, but dont remove nightlies-server -- it is nightlies server(obviously)

**Comment by Jolty95** [comment]
Done! All is getting really nice :) 
I have to keep working too in finishing NTRDBI. Should I upload a new test commit to make nightly server create it first build?

**Comment by OctoNezd** [comment]
Nah, nightly server is just for file storage: the actual things would happen in travis, I am working on upload script

**Comment by OctoNezd** [comment]
And I havent updated travis.yml yet

**Comment by Jolty95** [comment]
I had edited readme.md in local ready to upload when you are done :P

**Comment by OctoNezd** [comment]
Actually I thinked quite a bit and find out one thing: we can use NTRDB-Plugin-Host as storage for nightlies

**Comment by OctoNezd** [comment]
I need to lookup github API

**Comment by OctoNezd** [comment]
So, will it hurt if I add some files to this:https://github.com/adrifcastr/NTRDB-Plugin-Host/tree/NTRDBI-Update-Server ?

**Comment by Jolty95** [comment]
Use this better :P 
https://github.com/adrifcastr/NTRDB-Plugin-Host/tree/NTRDBI-Nightlies-Server

**Comment by OctoNezd** [comment]
So, we can even create nightly build update channel! Nice!

**Comment by OctoNezd** [comment]
Also, can I replace `"latest_micro": "1",` with `"latest_micro": "NIGHTLY",` then, or it will kill NTRDBI?

**Comment by Jolty95** [comment]
That will kill NTRDBI hahaha
Don't worry about that. In version 1.1 or 1.2, I'll implement settings where user can change between release and nighty channel :) (but for now, until 1.1, NTRDBI will always "update" to latest release :P )

**Comment by OctoNezd** [comment]
Travis begin building with latest changes.
Hope it will not explode.

**Comment by OctoNezd** [comment]
Aaand we failed
![image](https://cloud.githubusercontent.com/assets/15308404/24075532/5e2e0a28-0c2e-11e7-992f-c1a5add6b645.png)

**Comment by Jolty95** [comment]
Don't worry for .travis.yml, I'll fix the indentation later ;) 
And I'm fucking amazed by this, really!!

**Comment by Jolty95** [comment]
Do you know _where_ is crashing at least? I don't get any of this >.<

**Comment by OctoNezd** [comment]
I found bug. I forgot to make base64 as string, and I put `,` instead of `:` on line 17(headers)

**Comment by Jolty95** [comment]
Oh, that's good (I mean you found the bug, not it crash :P )

**Comment by OctoNezd** [comment]
Also it seems that I messed something up in request: github return 400

**Comment by OctoNezd** [comment]
> Oh, that's good (I mean you found the bug, not it crash :P )
I made it to catch all exceptions for not leaking mine Access Token

**Comment by OctoNezd** [comment]
![image](https://cloud.githubusercontent.com/assets/15308404/24075580/44b5e312-0c2f-11e7-8afe-228be8d2d7e3.png)

**Comment by Jolty95** [comment]
I'll upload updated readme.md if you don't mind :)

**Comment by Jolty95** [comment]
Is this the JSON? 

```
+        {"message": "[AUTO]NTRDBI Nightly build updated.",
+         "branch": "NTRDBI-Nightlies-Server",
+         "commiter": {
+             "name": "NTRDBI Nightly Builds"
+         },
+         "content": content
+         }
````

**Comment by OctoNezd** [comment]
Wait a second. I havent passed req anywhere 🤦‍♂️

**Comment by OctoNezd** [comment]
BOOM https://github.com/adrifcastr/NTRDB-Plugin-Host/commit/cd31f4a0d947e51080051c3028a4e58e989b33d4

**Comment by Jolty95** [comment]
YES!!!! Can you make it (if possible ofc) upload too latest cia (by date, commit hash, whatever in .cia format) in a folder called latest where all cias can be there?

**Comment by Jolty95** [comment]
(I have travis commit in local ready to push when you say :) )

**Comment by OctoNezd** [comment]
So I have two variants:
Replace build
Add build
I more like replacing it

**Comment by Jolty95** [comment]
That's all up to you (and easier for me if you keep it as replacing :P) 
Would you mind (again, only if you have time etc) to upload latest.cia too? I don't need it rn but I'll need it when NTRDBI can update to latest with update.json
(PS: I think message with hash can be good too

**Comment by OctoNezd** [comment]
The problem with swapping is this:
![image](https://cloud.githubusercontent.com/assets/15308404/24075719/a3c84ece-0c31-11e7-87a9-0312687f2940.png)
I cant understand what they mean by `blob SHA`. I will look into it tomorrow, because now it is 23:22 on mine clock

**Comment by Jolty95** [comment]
Again ( sometimes I don't explain very well )
-Replace NTRDBI.zip in server
-Add latest.cia in server
-Add to latest.cia and NTRDBI.zip in message, commit hash

**Comment by OctoNezd** [comment]
Commit hash is already in commit message
![image](https://cloud.githubusercontent.com/assets/15308404/24075732/e5ad9164-0c31-11e7-862f-8616cd9fa280.png)

**Comment by Jolty95** [comment]
It's OK, I tell you this morning to take a break :P (It's 21:23 on mine btw)

**Comment by Jolty95** [comment]
Yes, I know, just summarizing there

**Comment by OctoNezd** [comment]
We got some little problems
https://api.github.com/repos/adrifcastr/NTRDB-Plugin-Host/contents/NTRDBI.zip?ref=NTRDBI-Nightlies-Server
![image](https://cloud.githubusercontent.com/assets/15308404/24079507/a0487bca-0c9a-11e7-83ce-ff38d487be35.png)

**Comment by OctoNezd** [comment]
> -Replace NTRDBI.zip in server
-Add latest.cia in server
-Add to latest.cia and NTRDBI.zip in message, commit hash

Done!

**Comment by OctoNezd** [comment]
I can make download page for NTRDBI at octonezd.pw, if you want to

**Comment by Jolty95** [comment]
You can start creating it if you want and if you have time (you have spent some much time and I hate to bother) but not deploy it until release :)

**Comment by OctoNezd** [comment]
OK. I push into OctoNezd/octonezd.github.io after release. I would also need some screenshots(for showing how nice app is)

**Comment by Jolty95** [comment]
I'll send you some in other moment :P 
(BTW, FBI themes will be compatible too :D )

**Comment by OctoNezd** [comment]
Site is done, uploaded to adrifcast/NTRDB-Plugin-Host:NTRDBI-Web, not connected to octonezd,pw/ntrdbi yet

**Comment by Jolty95** [comment]
@OctoNezd  Thanks you for your time :)

**Comment by Jolty95** [comment]
BTW, if all it's done, I'll close here, and re-open or create another issue when I implement nightly channel!

**Comment by OctoNezd** [comment]
P.S. I added subdomain ntrdbi.octonezd.pw, currently it shows 404 page
