### ISSUE TITLE
Nightly Build Channel

### ISSUE THREAD

**Issue by OctoNezd** [adrifcastr/NTRDBI#12]
I can also implement swapping some things via python, if it needed for this

**Comment by Jolty95** [comment]
It's not needed :P I can do it with C on NTRDBI side :)

**Comment by OctoNezd** [comment]
But how NTRDBI will understand if it nightly build?

**Comment by Jolty95** [comment]
I just need an "if" inside NTRDBI to use latest.json or latest.cia

**Comment by OctoNezd** [comment]
But how we will divide nightly and stable? I suggest using custom title id and name, plus make major version = 0

**Comment by Jolty95** [comment]
I was thinking doing this in this way:

NTRDBI:
-RELEASE -> Have a new button to switch to Nightly builds. Release versions can be x.y.z without problems
-NIGHTLIES -> The same button, now have another text and switch to latest release. Nightlies builds versions are in format "xxxxxxxxxx" (commit short hash)

IN SERVER:
-RELEASE -> update.json will be the same*
-NIGHTLIES -> (Read *)

So, I only have to modify update.json in this way:

```
{
	"latest_major": "X",
	"latest_minor": "Y",
	"latest_micro": "Z",
	"release_url": "https://github.com/adrifcastr/NTRDB-Plugin-Host/blob/NTRDBI-Update-Server/NTRDBI.cia?raw=true"
        "nightly hash": "XXXXXXXXXX",
	"nightly_url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.latest.cia?raw=true"
}
```

This is my idea of how to archieve this. I'd like to still modify latest major, minor and micro by hand because I think is easier at least for me. Only thing that can be automated can be nightly hash but that is up to you :P

**Comment by OctoNezd** [comment]
How about pointing in latest.json of stable host to latest.json of nightly host?

**Comment by OctoNezd** [comment]
Mine idea is like this:

Nightlies has custom TitleID and version format is 0.0.{buildnumber}, and fetch data from nightly host

**Comment by Jolty95** [comment]
Because it's more difficult to parse a json of a json in NTRDBI code implementation :P (of course it can be done, but it's a bit more difficult :P )

**Comment by Jolty95** [comment]
I rather to not touch titleID and keep the same, so users can "revert" nightlies any time without deleting or installing two apps

**Comment by OctoNezd** [comment]
Apps can have different icon and romfs resources.

**Comment by Jolty95** [comment]
I mean to don't have two apps, only have one that can switch in any time

**Comment by OctoNezd** [comment]
Say me where update server url is located in sources, it could be easily autoswapped via .replace()

**Comment by OctoNezd** [comment]
What it nightly would have a critical bug which will don't allow to even launch it? User would get stuck

**Comment by Jolty95** [comment]
It's read by update.json. Also, https://github.com/adrifcastr/NTRDBI/issues/12#issuecomment-287707474 it still my point

**Comment by Jolty95** [comment]
> What it nightly would have a critical bug which will don't allow to even launch it? User would get stuck

That won't happen. Commits are always tested before pushing

**Comment by OctoNezd** [comment]
I still more prefer separation. Just to make sure that crap wont happen. Even if app is tested and all that stuff

**Comment by martinmontane** [comment]
Well I think I'll get to work on the database to do the nightly builds support.

**Comment by Jolty95** [comment]
We disagree but  respect your point. I think @adrifcastr should point us in this discussion

**Comment by Jolty95** [comment]
@martinmontane who are you? o.o

**Comment by OctoNezd** [comment]
Martin is one who implemented SQLite in NTRDB

**Comment by OctoNezd** [comment]
https://github.com/adrifcastr/NTRDBI/issues/12#issuecomment-287718722
What do you mean to update database? Make an nightly ver of NTRDB?

**Comment by Jolty95** [comment]
@OctoNezd didn't know that

**Comment by martinmontane** [comment]
All the plugin info is in the database, the download links every thing so what I'll do is add the column and make the functions in python so you can access and read everything

**Comment by OctoNezd** [comment]
Jolty can't into python

**Comment by Jolty95** [comment]
But why? If you both do that, I won't be able to make releases at all since all will be on your servers.

**Comment by OctoNezd** [comment]
Nonono, none of releases on mine server

**Comment by Jolty95** [comment]
I'm getting confuse, sorry  :sweat_smile:

**Comment by martinmontane** [comment]
I know jolty can't use python the python will be used by the server to update the API

**Comment by OctoNezd** [comment]
I can't understand what you want to do,@martinmontane

**Comment by martinmontane** [comment]
The link to the nightly builds. That is what I'm going o add to the database

**Comment by OctoNezd** [comment]
This is don't needed.
Nighty builds get automatically pushed to NTRDB-Plugin-Host:NTRDBI-Nightlies-Server

**Comment by martinmontane** [comment]
Oh srry to interrupt didn't know that, I'll just get to work on the top list for the website

**Comment by OctoNezd** [comment]
Also, I think it would be good idea for nightly builds have custom icon, colors

**Comment by Jolty95** [comment]
Icon and colors can be done without problems ;)

**Comment by OctoNezd** [comment]
But why you dislike separation?

**Comment by Jolty95** [comment]
At least for me is easier to only have one project and work on it but again, this is my opinion :P

**Comment by OctoNezd** [comment]
I still think it better to separate nightlies and stable. Because anyway, nightly build is nightly: it can do weird things

**Comment by Jolty95** [comment]
My idea is to have a "force" buttom at startup. I mean:
-Home menu
-User open nighty version
-Crash
What user can do?
a) reinstall cia again using FBI
b) 
   - Home menu
   - keep a key pressed (like B or X or whatever)
   - Force code is executed before master while loop so don't mind if ntrdbi crash, this code is executed always before
   - Download and install stable release cia directly (but not using the original method in app. here we will download and install cia instead of downloading and installing cia without writing it on sd)

**Comment by OctoNezd** [comment]
But what if some build settings broken and app tried to install .3ds and because of that it autoremoved itself?

**Comment by Jolty95** [comment]
I don't understand what you mean :(

**Comment by OctoNezd** [comment]
Nevermind.
So. What kind of delivering nightlies we will choose?

**Comment by OctoNezd** [comment]
![image](https://cloud.githubusercontent.com/assets/15308404/24103774/63d8d48a-0d91-11e7-8a95-2c7edf8bcfeb.png)
I tried compiling with "TEST" as VERSION_MAJOR

**Comment by Jolty95** [comment]
It won't compile at all since snprintf wants an integer not a char array. 
I don't mind at all to choose between the two ways of nightlies delivery and again, I think @adrifcastr have the last word to choose :P

**Comment by OctoNezd** [comment]
I dont belive @adrifcastr really care(sorry)

**Comment by OctoNezd** [comment]
So. I now preparing Nightly Builds customisation

**Comment by Jolty95** [comment]
I'm bussy rn, if you need some help ask me ;)

**Comment by OctoNezd** [comment]
Where you define version? I tried changing it in makefile, but Ver. 0.3.1 is still in status bar

**Comment by Jolty95** [comment]
Versions are defined in makefile. Remember to clean every before make anytime you modify makefile

**Comment by OctoNezd** [comment]
Script is done, testing now

**Comment by OctoNezd** [comment]
Hmm. App Update feature says for some reason error 404...

**Comment by OctoNezd** [comment]
Done. https://github.com/adrifcastr/NTRDBI/commit/658fb81d0573991cc70d24a15545cd84bef846bd
