### ISSUE TITLE
Make NTRDBI download and install plugins

### ISSUE THREAD

**Issue by Jolty95** [adrifcastr/NTRDBI#5]
- [x] Create plugin folder if it doesn't exist
- [x] Download plugin and rename correctly to it location
- [x] If title id is for an universal plugin, handle it too
- [x] Handle multi title ID plugins

**Comment by Jolty95** [comment]
I'll start doing this

**Comment by Jolty95** [comment]
1 out of 3 yeah!! 
Only two more!

**Comment by Jolty95** [comment]
2 out 3. Only one left!

There are a few things that needs to be modified on original API:
a) Name: we need to know the name .plg file needs to be
b) Download url: must be a .plg DIRECT download link. If not, it doesn't
download.
c) If url is a direct download link ending with xxxx.plg or
xxxx.plg?raw=true we can get a) from here instead. Also, I recommend to
move all plugins to our host repo

WIP: Use default layout with progress bar and parse "game" titleID

**Comment by OctoNezd** [comment]
Ok, I will get into that tomorrow

**Comment by Jolty95** [comment]
Thanks you @OctoNezd  👍

**Comment by OctoNezd** [comment]
I think name you should left as `name` var from JSON API.

Also, direct download links are required when user submits plugin, if no, I always reject this people.

**Comment by OctoNezd** [comment]
So I think we are ready to go and I should make a page for downloader, right?

If so, can you give me some In-Device screenshots?

**Comment by Jolty95** [comment]
@OctoNezd we are not ready for release yet. When it's ready, I'll notify It :)

**Comment by OctoNezd** [comment]
Btw, the problem with links is sitting between chair and computer :). It stated in /additem page that user should put a direct link, but looks like some people cant read, sadly :(
![image](https://cloud.githubusercontent.com/assets/15308404/23692421/7c5eee7e-03df-11e7-94f7-d6f13230e1d0.png)

**Comment by Jolty95** [comment]
@OctoNezd is there any way you as admin can modify the db entries? Just asking without "any" knowledge about web based db :P

**Comment by OctoNezd** [comment]
I can modify, but better thing is mail these people about their problem to make them update

**Comment by Jolty95** [comment]
Only one more to finish this section. Have some problem with .zip files

**Comment by Jolty95** [comment]
OK, this is done. But I need to know what will happen with this homebrew and host. @adrifcastr are you still leader of this homebrew?
