### ISSUE TITLE
Show plugin info

### ISSUE THREAD

**Issue by Jolty95** [adrifcastr/NTRDBI#7]
- [x] Add plugin info screen
- [x] Show plugin info

**Comment by Jolty95** [comment]
@adrifcastr need your opinion: do you want plugin pic been shown also in more info or only in description?

**Comment by OctoNezd** [comment]
I suggest generating an QR code when click on website.

**Comment by Jolty95** [comment]
@OctoNezd 👍  I like the idea. I will make when user press/click on website, a new window open and show QR in top screen and full url in bottom :) (but tomorrow :P)

**Comment by OctoNezd** [comment]
I can implement QR generation API if there is no one ported to 3DS

**Comment by Jolty95** [comment]
Do you say another api in your server or in C? I've found some QR librarys in C but I need to test them first :P

**Comment by OctoNezd** [comment]
Another api in server. Or implement rest

**Comment by Jolty95** [comment]
I don't mind. I have found some qr generator libraries for C if you don't wanna modify your server api
